// ADMIN
export const ADMIN_DASHBOARD_ROUTE              = '/admin'
export const ADMIN_APARTMENT_ROUTE              = '/admin/apartment'
export const ADMIN_CAR_ROUTE                    = '/admin/car'
export const ADMIN_DISEASE_ROUTE                = '/admin/disease'
export const ADMIN_DISTRICT_ROUTE               = '/admin/district'
export const ADMIN_DRIVER_ROUTE                 = '/admin/driver'
export const ADMIN_ENTRANCE_ROUTE               = '/admin/entrance'
export const ADMIN_FLOOR_ROUTE                  = '/admin/floor'
export const ADMIN_HOUSE_ROUTE                  = '/admin/house'
export const ADMIN_NEIGHBORHOOD_ROUTE           = '/admin/neighborhood'
export const ADMIN_OBJECT_ROUTE                 = '/admin/object'
export const ADMIN_POEPLE_ROUTE                 = '/admin/people'
export const ADMIN_SIDE_ROUTE                   = '/admin/side'
export const ADMIN_USER_ROUTE                   = '/admin/user'
// ADMIN ADD
export const ADMIN_ADD_APARTMENT_ROUTE          = '/admin/apartment/add'
export const ADMIN_ADD_CAR_ROUTE                = '/admin/car/add'
export const ADMIN_ADD_DISEASE_ROUTE            = '/admin/disease/add'
export const ADMIN_ADD_DISTRICT_ROUTE           = '/admin/district/add'
export const ADMIN_ADD_DRIVER_ROUTE             = '/admin/driver/add'
export const ADMIN_ADD_ENTRANCE_ROUTE           = '/admin/entrance/add'
export const ADMIN_ADD_FLOOR_ROUTE              = '/admin/floor/add'
export const ADMIN_ADD_HOUSE_ROUTE              = '/admin/house/add'
export const ADMIN_ADD_NEIGHBORHOOD_ROUTE       = '/admin/neighborhood/add'
export const ADMIN_ADD_OBJECT_ROUTE             = '/admin/object/add'
export const ADMIN_ADD_POEPLE_ROUTE             = '/admin/people/add'
export const ADMIN_ADD_SIDE_ROUTE               = '/admin/side/add'
export const ADMIN_ADD_USER_ROUTE               = '/admin/user/add'
// ADMIN GET
export const ADMIN_GET_APARTMENT_ROUTE          = '/admin/apartment/get'
export const ADMIN_GET_CAR_ROUTE                = '/admin/car/get'
export const ADMIN_GET_DISEASE_ROUTE            = '/admin/disease/get'
export const ADMIN_GET_DISTRICT_ROUTE           = '/admin/district/get'
export const ADMIN_GET_DRIVER_ROUTE             = '/admin/driver/get'
export const ADMIN_GET_ENTRANCE_ROUTE           = '/admin/entrance/get'
export const ADMIN_GET_FLOOR_ROUTE              = '/admin/floor/get'
export const ADMIN_GET_HOUSE_ROUTE              = '/admin/house/get'
export const ADMIN_GET_NEIGHBORHOOD_ROUTE       = '/admin/neighborhood/get'
export const ADMIN_GET_OBJECT_ROUTE             = '/admin/object/get'
export const ADMIN_GET_POEPLE_ROUTE             = '/admin/people/get'
export const ADMIN_GET_SIDE_ROUTE               = '/admin/side/get'
export const ADMIN_GET_USER_ROUTE               = '/admin/user/get'

// MANAGER
export const MANAGER_DASHBOARD_ROUTE            = '/manager'
export const MANAGER_APARTMENT_ROUTE            = '/manager/apartment'
export const MANAGER_CAR_ROUTE                  = '/manager/car'
export const MANAGER_DISEASE_ROUTE              = '/manager/disease'
export const MANAGER_DISEASEINFO_ROUTE          = '/manager/diseaseinfo'
export const MANAGER_DISTRICT_ROUTE             = '/manager/district'
export const MANAGER_DRIVER_ROUTE               = '/manager/driver'
export const MANAGER_ENTRANCE_ROUTE             = '/manager/entrance'
export const MANAGER_FLOOR_ROUTE                = '/manager/floor'
export const MANAGER_HOUSE_ROUTE                = '/manager/house'
export const MANAGER_OBJECT_ROUTE               = '/manager/object'
export const MANAGER_POEPLE_ROUTE               = '/manager/people'
export const MANAGER_SIDE_ROUTE                 = '/manager/side'
export const MANAGER_SHIFT_ROUTE                = '/manager/shift'
export const MANAGER_STATISTICS_ROUTE           = '/manager/statistics'
export const MANAGER_MAP_ROUTE                  = '/manager/map'
// MANAGER ADD
export const MANAGER_ADD_APARTMENT_ROUTE        = '/manager/apartment/add'
export const MANAGER_ADD_CAR_ROUTE              = '/manager/car/add'
export const MANAGER_ADD_DISEASE_ROUTE          = '/manager/disease/add'
export const MANAGER_ADD_DISEASEINFO_ROUTE      = '/manager/diseaseinfo/add'
export const MANAGER_ADD_DISTRICT_ROUTE         = '/manager/district/add'
export const MANAGER_ADD_DRIVER_ROUTE           = '/manager/driver/add'
export const MANAGER_ADD_ENTRANCE_ROUTE         = '/manager/entrance/add'
export const MANAGER_ADD_FLOOR_ROUTE            = '/manager/floor/add'
export const MANAGER_ADD_HOUSE_ROUTE            = '/manager/house/add'
export const MANAGER_ADD_OBJECT_ROUTE           = '/manager/object/add'
export const MANAGER_ADD_POEPLE_ROUTE           = '/manager/people/add'
export const MANAGER_ADD_SIDE_ROUTE             = '/manager/side/add'
export const MANAGER_ADD_SHIFT_ROUTE            = '/manager/shift/add'
// MANAGER GET
export const MANAGER_GET_APARTMENT_ROUTE        = '/manager/apartment/get'
export const MANAGER_GET_CAR_ROUTE              = '/manager/car/get'
export const MANAGER_GET_DISEASE_ROUTE          = '/manager/disease/get'
export const MANAGER_GET_DISTRICT_ROUTE         = '/manager/district/get'
export const MANAGER_GET_DISEASEINFO_ROUTE      = '/manager/diseaseinfo/get'
export const MANAGER_GET_DRIVER_ROUTE           = '/manager/driver/get'
export const MANAGER_GET_ENTRANCE_ROUTE         = '/manager/entrance/get'
export const MANAGER_GET_FLOOR_ROUTE            = '/manager/floor/get'
export const MANAGER_GET_HOUSE_ROUTE            = '/manager/house/get'
export const MANAGER_GET_OBJECT_ROUTE           = '/manager/object/get'
export const MANAGER_GET_POEPLE_ROUTE           = '/manager/people/get'
export const MANAGER_GET_SIDE_ROUTE             = '/manager/side/get'
export const MANAGER_GET_SHIFT_ROUTE            = '/manager/shift/get'

// OPERATOR
export const OPERATOR_DASHBOARD_ROUTE           = '/operator'
export const OPERATOR_STATISTICS_ROUTE          = '/operator/statistics'

// STATISTICS
export const STATISTICS_DASHBOARD_ROUTE         = '/statistics'

// GENERAL  
export const LOGIN_ROUTE                        = '/'